["Actor: Dependabot"]
color = "025E8C"
name = "Actor: Dependabot"
description = "Action by Dependabot"

["Area: Testing"]
color = "fcc7f0"
name = "Area: Testing"
description = "Testing"

["Area: Ansible"]
color = "fcc7f0"
name = "Area: Ansible"
description = ""

["Priority: Critical"]
color = "FF0000"
name = "Priority: Critical"
description = "Urgent/Extremely important"

["Priority: High"]
color = "FFA500"
name = "Priority: High"
description = "High importance"

["Priority: Low"]
color = "85e595"
name = "Priority: Low"
description = "Low prioirty tasks"

["Priority: Medium"]
color = "fbca04"
name = "Priority: Medium"
description = "Medium priority PR/issues"

["Status: Awaiting-Response"]
color = "00b1ed"
name = "Status: Awaiting-Response"
description = ""

["Status: Keep-Open"]
color = "00b1ed"
name = "Status: Keep-Open"
description = ""

["Status: Abandoned"]
color = "000000"
name = "Status: Abandoned"
description = "Issue/feature has been abandoned."

["Status: Done"]
color = "00FF9F"
name = "Status: Done"
description = "Completed and closed tasks/pr/issues"

["Status: In-Progress"]
color = "FFD649"
name = "Status: In-Progress"
description = "PR/Bug-fix WIP"

["Status: Resolved"]
color = "00D100"
name = "Status: Resolved"
description = "Issue/PR has been resolved"

["Status: Review Required"]
color = "C4FF36"
name = "Status: Review Required"
description = "Further review required"

["Status: Stale"]
color = "ffffff"
name = "Status: Stale"
description = ""

["Status: WontFix"]
color = "AFAFED"
name = "Status: WontFix"
description = "Works as intended/beyond scope"

["Type: Bug"]
color = "e11d21"
name = "Type: Bug"
description = "Issue is a bug, Add Type: BugFix for PR"

["Type: Documentation"]
color = "fca6da"
name = "Type: Documentation"
description = "Docs"

["Type: Duplicate"]
color = "C8A2C8"
name = "Type: Duplicate"
description = "Issue or PR is duplicate"

["Type: Enhancement"]
color = "84b6eb"
name = "Type: Enhancement"
description = "Improve existing feature"

["Type: Feature"]
color = "7eed76"
name = "Type: Feature"
description = "Feature request/new feature"

["Type: Maintenance"]
color = "f4aea1"
name = "Type: Maintenance"
description = "Maintenance tasks/package updates/prettify etc"

["Deps: Docker"]
color = "ceef86"
name = "Deps: Docker"
description = ""

["Deps: Go"]
color = "ceef86"
name = "Deps: Go"
description = ""

["Deps: Python"]
color = "ceef86"
name = "Deps: Python"
description = "Python Deps"

["Deps: Rust"]
color = "ceef86"
name = "Deps: Rust"
description = ""

["Deps: Submodule"]
color = "ceef86"
name = "Deps: Submodule"
description = ""
