# terraform-docs version
version: ">= 0.13.0, < 1.0.0"

formatter: markdown table

sort:
  enabled: true
  by: required

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->

    {{ .Content }}

    <!-- END_TF_DOCS -->
