# yamllint disable-line rule:document-start
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - ".gitignore"
      - ".envrc"
      - "**.md"
      - ".vscode/**"
      - ".dependabot/**"
  pull_request:
    branches:
      - master
name: terraform
jobs:
  lint:
    name: 'terraform'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tfv: [0.13.5]
    env:
      LIBVIRT_DEFAULT_URI: "qemu:///system"
      # UNDOC:: Force use qemu on actions
      TERRAFORM_LIBVIRT_TEST_DOMAIN_TYPE: "qemu"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: {{ matrix.tfv }}
      - name: Permission fixer
        run: |
            sudo mkdir -p /etc/libvirt
            sudo chmod 755 /etc/libvirt
            echo 'security_driver="none"' | sudo tee /etc/libvirt/qemu.conf
      - name: Install Provider
        run: |
          make install-provider
      - name: Install Packages
        run: |
            sudo apt-get -qq update
            sudo apt-get install -qq -y \
              libvirt-daemon-system \
              libvirt-dev \
              python3-libvirt \
              virt-manager \
              mkisofs \
              python3-pip \
              python3-setuptools \
              python3-libvirt \
              python3-lxml
      - name: Platform Info
        run: |
            echo "KVM Status"
            echo "-----------"
            # Because kvm-ok might return non zero we will make it drink some truth serum
            sudo kvm-ok || true
            # Daemon
            echo "-----------"
            echo "Restarting Daemon"
            sudo systemctl reload libvirtd
            echo "Status of Daemon"
            sudo systemctl status libvirtd
            # Host status
            echo "Host Validation"
            echo "-----------"
            sudo -E virt-host-validate || true
      - name: 'Terraform Format'
        run: make fmt-lint
      - name: 'Terraform Validate'
        # MUST run as sudo
        run: sudo -E make validate
      - name: Start default pool
        run: |
          sudo mkdir -p /var/lib/libvirt/images
          sudo virsh pool-define test/default-pool.xml
          sudo virsh pool-start default
      - name: Install Assert dependencies
        run: |
          python get-poetry.py -y
          source $HOME/.poetry/env
          poetry export -o requirements.txt
      - name: Install Test dependencies
        run: |
          sudo pip3 install -r requirements.txt
          sudo -H -E make assert-ubuntu